baseURL = "http://examplesite.org/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "ESI Soluções Industriais"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "Sobre nós"
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
[[menu.footer_left]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "#"
name = "Platform"
[[menu.footer_middle]]
URL = "#"
name = "Features"
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
[[menu.footer_right]]
URL = "faq"
name = "FAQ"
[[menu.main]]
URL = "Valores"
name = "Valores"
weight = 3
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
description = "This is meta description"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
logo = "images/logo.png"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Contato"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
