baseURL = "http://esisolucoes.com.br"
disqusShortname = ""
googleAnalytics = "UA-175470417-1"
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "ESI Soluções Industriais"
[markup.goldmark.renderer]
unsafe = true
[menu]
footer_middle = ["Charrua Parts"]
footer_right = []
[[menu.footer_left]]
URL = ""
name = "Sobre nós"
[[menu.footer_left]]
URL = ""
name = "Github"
[[menu.main]]
URL = "privacy-policy"
name = "Sobre nós"
weight = 3
[[menu.main]]
URL = "terms-conditions"
name = "Projetos"
weight = ""
[params]
author = "Guilherme Andrade"
contact_form_action = "#"
copyright = "Develop by [Guilherme Andrade](https://gethugothemes.com/)"
description = "This is meta description"
footer_content = "BR-158, Via Lateral Doricó Tartari, 5450 <br> 85503-260, Fraron, Pato Branco <br>Paraná, Brasil <br>+55 (46) 99913-6201 <br> esisolucoesindustriais@gmail.com"
footer_menu_left = "Links úteis"
footer_menu_middle = "Mais informações"
footer_menu_right = "Lado 3"
logo = "images/logo.png"
logo_width = "150px"
[params.navigation_button]
enable = true
label = "Contato"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/esisolucoesindustriais"
title = "linkedin"
